version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:8081/api
      - VITE_SOCKET_URL=http://localhost:8081
      - VITE_APP_ENV=development

  server:
    build:
      context: ./server
    ports:
      - "8081:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=setlist_builder_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRATION=24h
      - JWT_REFRESH_EXPIRATION=7d
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5242880
      - CORS_ORIGIN=http://localhost:8080
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100

  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=setlist_builder_db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
